### ISSUE TITLE
ModuleNotFoundError: No module named 'lsp_jsonrpc'

### ISSUE THREAD

**Issue by Juan-hwt** [microsoft/vscode-autopep8#110]
2023-06-16 15:47:40.917 [info] Name: autopep8
2023-06-16 15:47:40.917 [info] Module: autopep8
2023-06-16 15:47:40.917 [info] Python extension loading
2023-06-16 15:47:40.917 [info] Waiting for interpreter from python extension.
2023-06-16 15:47:40.917 [info] Python extension loaded
2023-06-16 15:47:40.917 [info] Server run command: d:\tools\python-3.9.13\python.exe c:\Users\tiancom\.vscode\extensions\ms-python.autopep8-2023.4.0\bundled\tool\lsp_server.py
2023-06-16 15:47:40.917 [info] Server: Start requested.
2023-06-16 15:47:40.998 [info] Traceback (most recent call last):
  File "c:\Users\tiancom\.vscode\extensions\ms-python.autopep8-2023.4.0\bundled\tool\lsp_server.py", line 38, in <module>

2023-06-16 15:47:40.998 [info]     import lsp_jsonrpc as jsonrpc
ModuleNotFoundError: No module named 'lsp_jsonrpc'

2023-06-16 15:47:41.006 [info] [Error - 15:47:41] Server initialization failed.
2023-06-16 15:47:41.006 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-06-16 15:47:41.006 [info] [Info  - 15:47:41] Connection to server got closed. Server will restart.
2023-06-16 15:47:41.006 [info] true
2023-06-16 15:47:41.007 [info] [Error - 15:47:41] autopep8 client: couldn't create connection to server.
2023-06-16 15:47:41.007 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-06-16 15:47:41.103 [info] Traceback (most recent call last):
  File "c:\Users\tiancom\.vscode\extensions\ms-python.autopep8-2023.4.0\bundled\tool\lsp_server.py", line 38, in <module>

2023-06-16 15:47:41.103 [info]     import lsp_jsonrpc as jsonrpc
ModuleNotFoundError: No module named 'lsp_jsonrpc'

2023-06-16 15:47:41.107 [info] [Error - 15:47:41] Server initialization failed.
2023-06-16 15:47:41.107 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-06-16 15:47:41.107 [info] [Info  - 15:47:41] Connection to server got closed. Server will restart.
2023-06-16 15:47:41.107 [info] true
2023-06-16 15:47:41.108 [info] [Error - 15:47:41] autopep8 client: couldn't create connection to server.
2023-06-16 15:47:41.108 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-06-16 15:47:41.108 [error] Server: Start failed: Error: Pending response rejected since connection got disposed
2023-06-16 15:47:41.190 [info] Traceback (most recent call last):
  File "c:\Users\tiancom\.vscode\extensions\ms-python.autopep8-2023.4.0\bundled\tool\lsp_server.py", line 38, in <module>

2023-06-16 15:47:41.190 [info]     import lsp_jsonrpc as jsonrpc
ModuleNotFoundError: No module named 'lsp_jsonrpc'

2023-06-16 15:47:41.195 [info] [Error - 15:47:41] Server initialization failed.
2023-06-16 15:47:41.195 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-06-16 15:47:41.195 [info] [Info  - 15:47:41] Connection to server got closed. Server will restart.
2023-06-16 15:47:41.195 [info] true
2023-06-16 15:47:41.195 [info] [Error - 15:47:41] autopep8 client: couldn't create connection to server.
2023-06-16 15:47:41.195 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-06-16 15:47:41.195 [info] [Error - 15:47:41] Restarting server failed
2023-06-16 15:47:41.196 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-06-16 15:47:41.307 [info] Traceback (most recent call last):
  File "c:\Users\tiancom\.vscode\extensions\ms-python.autopep8-2023.4.0\bundled\tool\lsp_server.py", line 38, in <module>

2023-06-16 15:47:41.307 [info]     import lsp_jsonrpc as jsonrpc
ModuleNotFoundError: No module named 'lsp_jsonrpc'

2023-06-16 15:47:41.313 [info] [Error - 15:47:41] Server initialization failed.
2023-06-16 15:47:41.313 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-06-16 15:47:41.313 [info] [Info  - 15:47:41] Connection to server got closed. Server will restart.
2023-06-16 15:47:41.313 [info] true
2023-06-16 15:47:41.313 [info] [Error - 15:47:41] autopep8 client: couldn't create connection to server.
2023-06-16 15:47:41.313 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-06-16 15:47:41.314 [info] [Error - 15:47:41] Restarting server failed
2023-06-16 15:47:41.314 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-06-16 15:47:41.399 [info] Traceback (most recent call last):
  File "c:\Users\tiancom\.vscode\extensions\ms-python.autopep8-2023.4.0\bundled\tool\lsp_server.py", line 38, in <module>
    import lsp_jsonrpc as jsonrpc
ModuleNotFoundError: No module named 'lsp_jsonrpc'

2023-06-16 15:47:41.406 [info] [Error - 15:47:41] Server initialization failed.
2023-06-16 15:47:41.406 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-06-16 15:47:41.406 [info] [Error - 15:47:41] The autopep8 server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
2023-06-16 15:47:41.406 [info] [Error - 15:47:41] autopep8 client: couldn't create connection to server.
2023-06-16 15:47:41.406 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-06-16 15:47:41.406 [info] [Error - 15:47:41] Restarting server failed
2023-06-16 15:47:41.406 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 

with vscode reinstalled
![image](https://github.com/microsoft/vscode-autopep8/assets/82884966/66032d60-16a6-43ab-a6cb-979075eeb597)

with python version 3.9 reinstalled

it always failed to start, how to fix it? thank you

**Comment by karthiknadig** [comment]
Can you go to this folder and do a `dir`?
```
> cd c:\Users\tiancom.vscode\extensions\ms-python.autopep8-2023.4.0\bundled\tool\
> dir
```
the output should look like this:
![image](https://github.com/microsoft/vscode-autopep8/assets/3840081/809e1319-58ba-434b-8035-88d97536232f)

**Comment by Juan-hwt** [comment]
![微信图片_20230617201231](https://github.com/microsoft/vscode-autopep8/assets/82884966/fb240824-058d-4a6f-ae82-478580410595)

**Comment by karthiknadig** [comment]
@Juan-hwt That looks like the `lsp_jsonrpc.py` you have is corrupt. Please uninstall `vscode-autopep8`, close all instances of vscode, delete `C:\Users\tiancom\.vscode\extensions\ms-python.autopep8-2023.4.0` folder. Then re-install it from the market place.

**Comment by Juan-hwt** [comment]
> @Juan-hwt That looks like the `lsp_jsonrpc.py` you have is corrupt. Please uninstall `vscode-autopep8`, close all instances of vscode, delete `C:\Users\tiancom\.vscode\extensions\ms-python.autopep8-2023.4.0` folder. Then re-install it from the market place.

I have done it but the same ...reboot ....  no working ... I don't know why ....  always like this ... if is it the problem with system?

**Comment by karthiknadig** [comment]
Can you check `lsp_jsonrpc.py` size again, it should be like the image I shared. If it is different, then something is getting corrupted on your machine. We can move this issue to VS Code to see what is going on.

**Comment by Juan-hwt** [comment]
![1687236000802](https://github.com/microsoft/vscode-autopep8/assets/82884966/b8d1c561-f5bd-49f9-941e-b0900849b934)

**Comment by karthiknadig** [comment]
That looks right. Can toy try running this from the command line? this is really strange, all the files are present but for some reason it is not able to import.
```
> d:\tools\python-3.9.13\python.exe c:\Users\tiancom.vscode\extensions\ms-python.autopep8-2023.4.0\bundled\tool\lsp_server.py
```

Note, there will be no output, it should simply be blank. If there is any error then that means something is wrong.

**Comment by Juan-hwt** [comment]
run as admin and give me: Access to the file is denied
so that is the problem... how to change it?

**Comment by karthiknadig** [comment]
You were previously able to do `dir`  in the directory. Before you do anything `cd` to your project directory, you may not be able to run this from your home directory.

Try running just the python first to see if that works:
```
> d:\tools\python-3.9.13\python.exe
```
That should load python, if it does then `exit()` from it. and try this command again:
```
> type c:\Users\tiancom\.vscode\extensions\ms-python.autopep8-2023.4.0\bundled\tool\lsp_server.py
```
That should print out the source code. Then try running the server command:
```
> d:\tools\python-3.9.13\python.exe c:\Users\tiancom\.vscode\extensions\ms-python.autopep8-2023.4.0\bundled\tool\lsp_server.py
```
This should be blank, but no errors.

**Comment by Juan-hwt** [comment]
> You were previously able to do `dir` in the directory. Before you do anything `cd` to your project directory, you may not be able to run this from your home directory.
> 
> Try running just the python first to see if that works:
> 
> ```
> > d:\tools\python-3.9.13\python.exe
> ```
> 
> That should load python, if it does then `exit()` from it. and try this command again:
> 
> ```
> > type c:\Users\tiancom\.vscode\extensions\ms-python.autopep8-2023.4.0\bundled\tool\lsp_server.py
> ```
> 
> That should print out the source code. Then try running the server command:
> 
> ```
> > d:\tools\python-3.9.13\python.exe c:\Users\tiancom\.vscode\extensions\ms-python.autopep8-2023.4.0\bundled\tool\lsp_server.py
> ```
> 
> This should be blank, but no errors.
follow the third :

![image](https://github.com/microsoft/vscode-autopep8/assets/82884966/88ad1c06-2329-41bf-b012-f7c4fefcd04d)

so i think it is the problem of vscode, in this years more difficult to use 
I even think to choose another ide . 

We can move this issue to VS Code to see what is going on.
----- you need to tell them ,worse than before. Woooo, always with problem, version, unicode,  ........ waste time

**Comment by Juan-hwt** [comment]
python.exe c:\Users\tiancom\.vscode\extensions\ms-python.autopep8-2023.4.0\bundled\tool\lsp_server.py

no response 


2023-06-20 21:28:10.146 [info] Name: autopep8
2023-06-20 21:28:10.147 [info] Module: autopep8
2023-06-20 21:28:10.176 [error] Python version undefined.undefined is not supported.
2023-06-20 21:28:10.176 [error] Selected python path: undefined
2023-06-20 21:28:10.176 [error] Supported versions are 3.7 and above.
2023-06-20 21:28:10.185 [info] Server run command: autopep8.interpreter c:\Users\tiancom\.vscode\extensions\ms-python.autopep8-2023.4.0\bundled\tool\lsp_server.py
2023-06-20 21:28:10.185 [info] Server: Start requested.
2023-06-20 21:28:10.209 [info] [Error - 21:28:10] autopep8 client: couldn't create connection to server.
2023-06-20 21:28:10.209 [info] Launching server using command autopep8.interpreter failed. Error: spawn autopep8.interpreter ENOENT
2023-06-20 21:28:10.210 [error] Server: Start failed: Launching server using command autopep8.interpreter failed. Error: spawn autopep8.interpreter ENOENT

**Comment by karthiknadig** [comment]
@Juan-hwt CAn you try the pre-release version. I added a few fixes that should help with this issue.

**Comment by Juan-hwt** [comment]
try the pre-release version like this：
2023-07-06 09:00:39.797 [info] Name: autopep8
2023-07-06 09:00:39.797 [info] Module: autopep8
2023-07-06 09:00:39.824 [error] Python version undefined.undefined is not supported.
2023-07-06 09:00:39.824 [error] Selected python path: undefined
2023-07-06 09:00:39.824 [error] Supported versions are 3.7 and above.
2023-07-06 09:00:39.927 [info] Server run command: autopep8.interpreter c:\Users\tiancom\.vscode\extensions\ms-python.autopep8-2023.4.0\bundled\tool\lsp_server.py
2023-07-06 09:00:39.927 [info] Server: Start requested.
2023-07-06 09:00:39.933 [info] [Error - 09:00:39] autopep8 client: couldn't create connection to server.
2023-07-06 09:00:39.933 [info] Launching server using command autopep8.interpreter failed. Error: spawn autopep8.interpreter ENOENT
2023-07-06 09:00:39.933 [error] Server: Start failed: Launching server using command autopep8.interpreter failed. Error: spawn autopep8.interpreter ENOENT

**Comment by karthiknadig** [comment]
@Juan-hwt You are still installing `2023.4.0`, please install `2023.5`:
![image](https://github.com/microsoft/vscode-autopep8/assets/3840081/1f607507-be3b-4b5a-9070-3b7d4814b635)

it should show this version:
![image](https://github.com/microsoft/vscode-autopep8/assets/3840081/dd38bc96-1838-4580-91f1-372395310fe0)

**Comment by Juan-hwt** [comment]
2023-07-06 12:39:33.003 [info] Name: autopep8
2023-07-06 12:39:33.003 [info] Module: autopep8
2023-07-06 12:39:33.003 [info] Interpreter from setting autopep8.interpreter: autopep8.interpreter
2023-07-06 12:39:33.003 [info] Interpreter from setting autopep8.interpreter: autopep8.interpreter
2023-07-06 12:39:33.003 [info] Server run command: autopep8.interpreter c:\Users\tiancom\.vscode\extensions\ms-python.autopep8-2023.5.11781018\bundled\tool\lsp_server.py
2023-07-06 12:39:33.003 [info] Server: Start requested.
2023-07-06 12:39:33.003 [info] [Error - 12:39:32] autopep8 client: couldn't create connection to server.
2023-07-06 12:39:33.003 [info] Launching server using command autopep8.interpreter failed. Error: spawn autopep8.interpreter ENOENT
2023-07-06 12:39:33.003 [error] Server: Start failed: Launching server using command autopep8.interpreter failed. Error: spawn autopep8.interpreter ENOENT

![1688618429662](https://github.com/microsoft/vscode-autopep8/assets/82884966/9ead51be-2862-4d42-ae26-c00b80591367)

**Comment by karthiknadig** [comment]
There is something wrong with your settings, if yAou have no python selected it should look like this:
![image](https://github.com/microsoft/vscode-autopep8/assets/3840081/79ceeaf1-36ae-4c06-ab6c-f3bcabe7d8cd)


If you have python selected it should look like this:
![image](https://github.com/microsoft/vscode-autopep8/assets/3840081/a0830ed0-a8f0-4a82-9a9f-60af29ab84e5)

Your setting here looks really weird:
![image](https://github.com/microsoft/vscode-autopep8/assets/3840081/71f23465-387e-4468-beeb-f3706bce2ed8)

Can you share your workspace setting, and user setting? 
follow this video to get the settings.

https://github.com/microsoft/vscode-autopep8/assets/3840081/32cd4cfd-a9f5-49b0-9a1c-f2e6a7a64866

**Comment by Juan-hwt** [comment]
`
{
    "workbench.colorTheme": "Quiet Light",
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "ms-python.autopep8",
    "[jsonc]": {
        "editor.defaultFormatter": "vscode.json-language-features"
    },
    "python.defaultInterpreterPath": "C:\\Users\\tiancom\\AppData\\Local\\Programs\\Python\\Python311\\",
    "autopep8.interpreter": [
        "autopep8.interpreter"
    ],
    "python.formatting.autopep8Path": "",
    "Codegeex.Privacy": true,
    "[python]": {
        "diffEditor.ignoreTrimWhitespace": false,
        "editor.formatOnType": true,
        "editor.wordBasedSuggestions": false
    }
}
`
and the second like this:
{
}

**Comment by karthiknadig** [comment]
@Juan-hwt The following settings are wrong. Please remove them:
```
"python.defaultInterpreterPath": "C:\Users\tiancom\AppData\Local\Programs\Python\Python311\",
"autopep8.interpreter": ["autopep8.interpreter"],
```
`python.defaultInterpreterPath` should point to a binary not a folder, so if you want to use the setting it should be pointing to some `python.exe`. For example `C:\Users\tiancom\AppData\Local\Programs\Python\Python311\python.exe`. Make sure to check this exists: C:\Users\tiancom\AppData\Local\Programs\Python\Python311\python.exe

`"autopep8.interpreter": ["autopep8.interpreter"]` You cannot set that to `"autopep8.interpreter"` it makes no sense. There is no need to use this if you have python extension installed and you use it to select a python. If you want to use it, it should also point to `python.exe`. `"autopep8.interpreter": ["C:\Users\tiancom\AppData\Local\Programs\Python\Python311\python.exe"]`

For now try without those settings:
```
{
"workbench.colorTheme": "Quiet Light",
"editor.formatOnSave": true,
"editor.defaultFormatter": "ms-python.autopep8",
"[jsonc]": {
"editor.defaultFormatter": "vscode.json-language-features"
},
"Codegeex.Privacy": true,
"[python]": {
"diffEditor.ignoreTrimWhitespace": false,
"editor.formatOnType": true,
"editor.wordBasedSuggestions": false
}
}
```

**Comment by Juan-hwt** [comment]
"python.defaultInterpreterPath": "C:\Users\tiancom\AppData\Local\Programs\Python\Python311\",
"autopep8.interpreter": ["autopep8.interpreter"],

I deleted those sentences, server started, all seems good, but
with alt + shift + f , no working

change settings, ok

but thats setences is not of mine hands, it's automaticly writing when installing

for all, thank you so much!

**Comment by karthiknadig** [comment]
@Juan-hwt If `alt+shift+f` is not working check logs. It should have some details there if `format` was triggered. Also check your key bindings.
![image](https://github.com/microsoft/vscode-autopep8/assets/3840081/8841287c-24d7-4449-9fca-4344a6d9d6ee)

![image](https://github.com/microsoft/vscode-autopep8/assets/3840081/23f15650-4c2b-4c69-aecb-619ee8c9fa8b)
