### ISSUE TITLE
Can not format when I use it in single file

### ISSUE THREAD

**Issue by 1m188** [microsoft/vscode-autopep8#127]
When I want to format my file when I do not open an activate workspace, (just open a single file), it doesn't work.
When I format a file with a opened workspace, (this file is not in this workspace) it also doesn't work.
It only work when I open a workspace and open a file which in actually in this workspace.
I hope it can work well in any situations.

**Comment by karthiknadig** [comment]
@1m188 Can you share the logs from Output > autopep8? Make sure this is the case where it is not working.

**Comment by 1m188** [comment]
emmm, when I format my file, it show notification like this:


Traceback (most recent call last):
  File "c:\Users\user name\.vscode\extensions\ms-python.autopep8-2023.6.0\bundled\tool\lsp_server.py", line 429, in _run_tool_on_document
    result = utils.run_module(
  File "c:\Users\user name\.vscode\extensions\ms-python.autopep8-2023.6.0\bundled\tool\lsp_utils.py", line 153, in run_module
    return _run_module(module, argv, use_stdin, source)
  File "c:\Users\user name\.vscode\extensions\ms-python.autopep8-2023.6.0\bundled\tool\lsp_utils.py", line 138, in _run_module
    runpy.run_module(module, run_name="__main__")
  File "c:\Users\user name\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 228, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "c:\Users\user name\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\user name\.vscode\extensions\ms-python.autopep8-2023.6.0\bundled\libs\autopep8.py", line 414, in <module>
    del pycodestyle._checks['logical_line'][pycodestyle.continued_indentation]
KeyError: <function continued_indentation at 0x000001A78FDC8820>

**Comment by karthiknadig** [comment]
Can you share the initial part of the logs where settings are passed?
