### ISSUE TITLE
Mistake in python 3.7(autopep8 v2022.1.12871025)

### ISSUE THREAD

**Issue by inkoff** [microsoft/vscode-autopep8#15]
```
Traceback (most recent call last):
  File "C:\Users\Oleg Kolesov\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Oleg Kolesov\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\Oleg Kolesov\.vscode\extensions\ms-python.autopep8-2022.1.12871025\bundled\libs\autopep8.py", line 4590, in <module>
    sys.exit(main())
  File "c:\Users\Oleg Kolesov\.vscode\extensions\ms-python.autopep8-2022.1.12871025\bundled\libs\autopep8.py", line 4536, in main
    wrap_output(sys.stdout, encoding=encoding).write(fixed_stdin)
  File "C:\Users\Oleg Kolesov\AppData\Local\Programs\Python\Python37\lib\codecs.py", line 377, in write
    data, consumed = self.encode(object, self.errors)
  File "C:\Users\Oleg Kolesov\AppData\Local\Programs\Python\Python37\lib\encodings\cp1251.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character '\udc98' in position 255: character maps to \<undefined\>
```

**Comment by karthiknadig** [comment]
@inkoff Does running autopep8 from your terminal using the same python work? Can you share your environment variables?

**Comment by karthiknadig** [comment]
Because we have not heard back with the information we requested, we are closing this issue for now. If you are able to provide the info later on then we will be happy to re-open this issue to pick up where we left off.
