### ISSUE TITLE
formatter does not work if it contains a specific string

### ISSUE THREAD

**Issue by LCH-1** [microsoft/vscode-autopep8#51]
first, my settings.py
![image](https://user-images.githubusercontent.com/55623558/214276178-663dd06f-0e72-4888-82e9-f8d3a3363437.png)

Normally, it works fine.
But it doesn't work if it contains special characters.
![test](https://user-images.githubusercontent.com/55623558/214277093-8f9accee-5800-4346-81a0-22861dc87005.gif)

I tested in Korean, but the same phenomenon occurred when Japanese or certain special characters were included.

Is there a way to resolve the issue?

**Comment by karthiknadig** [comment]
@LCH-1 This feels like an issue with `autopep8` itself. What do you see in Output > autopep8 ?

**Comment by LCH-1** [comment]
```
c:\Program Files\Python310\python.exe -m autopep8 -
CWD Server: c:\Users\ckdgh\AppData\Local\Programs\Microsoft VS Code
Traceback (most recent call last):
  File "c:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\ckdgh\.vscode\extensions\ms-python.autopep8-2022.3.13271012\bundled\libs\autopep8.py", line 4585, in <module>
    sys.exit(main())
  File "c:\Users\ckdgh\.vscode\extensions\ms-python.autopep8-2022.3.13271012\bundled\libs\autopep8.py", line 4531, in main
    wrap_output(sys.stdout, encoding=encoding).write(fixed_stdin)
UnicodeEncodeError: 'cp949' codec can't encode character '\udced' in position 18: illegal multibyte sequence
```
This is the output when special character is included and does not work.

**Comment by karthiknadig** [comment]
@LCH-1 does this happen if you run the command from the terminal:
```
set PYTHONPATH=c:\Users\user\.vscode\extensions\ms-python.autopep8-2022.3.13271012\bundled\libs
type <python file> | c:\Program Files\Python310\python.exe -m autopep8 -
```

**Comment by LCH-1** [comment]
The same problem happens.
```
C:\Users\user\Desktop>set PYTHONPATH=c:\Users\user\.vscode\extensions\ms-python.autopep8-2022.3.13271012\bundled\libs

C:\Users\user\Desktop>type test.py  | "c:\Program Files\Python310\python.exe" -m autopep8 -
Traceback (most recent call last):
  File "c:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\user\.vscode\extensions\ms-python.autopep8-2022.3.13271012\bundled\libs\autopep8.py", line 4585, in <module>
    sys.exit(main())
  File "c:\Users\user\.vscode\extensions\ms-python.autopep8-2022.3.13271012\bundled\libs\autopep8.py", line 4531, in main
    wrap_output(sys.stdout, encoding=encoding).write(fixed_stdin)
UnicodeEncodeError: 'cp949' codec can't encode character '\udced' in position 18: illegal multibyte sequence
```

**Comment by karthiknadig** [comment]
@LCH-1 Thanks for looking into this. The issue is in `autopep8` itself. You should file that here: https://github.com/hhatto/autopep8/issues.
